// <auto-generated />
namespace ShinGin_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTb_Statistics_2st : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTb_Statistics_2st));
        
        string IMigrationMetadata.Id
        {
            get { return "202305291347328_AddTb_Statistics_2st"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
